### ISSUE TITLE
Pre-build Klaros docker images

### ISSUE THREAD

**Issue by PromoFaux** [klaros-testmanagement/klaros-docker#57]
Hi there, would you have any interest in having pre-built images available, either on Docker Hub or here on Github? The latter is super simple to set up and I would be more than happy to provide a PR with the relevant changes to the Github Actions workflow. 

How I see it:
  - You create the release/tag on this repository when you are ready for a new release
  -  Workflow kicks in to build the Klaros containers (only the Klaros application Dockerfiles, not the Database ones) and pushes them to the container registry here
  - The images can automatically be tagged correctly, i.e `ghcr.io/klaros-testmanagement/klaros-docker:v5.3.0-databaseType` (and even a plain `klaros-docker:databaseType` which is always the latest available for that type)

I started thinking about this yesterday when I was building/rebuilding the container locally - and each time it had to download the `setup.jar` file, which could take upwards of 20/30 mins - might also prevent your bandwidth from being hammered when pesky people like me are constantly building the image ;)

I already took a look at simplifying the workflow file yesterday: https://github.com/PromoFaux/klaros-docker/actions/runs/1342274759/workflow

With a couple of tweaks, it can be made to also upload that image to the GitHub Container Registry, see here for an example of where I have done this on another project: 

https://github.com/pi-hole/docker-base-images/blob/master/.github/workflows/ftl-build.yml#L48-L61

Edit: Working example https://github.com/PromoFaux/klaros-docker/pkgs/container/klaros

**Comment by stolp** [comment]
Sorry for answering late we had an unexpected outage to cope with today.

Your addition is highly welcome! If there are hurdles like the TOMCAT_ADMIN_PASSWORD mentioned we are open to discuss a better solution.
